services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=workwell'
      - 'POSTGRES_PASSWORD=workwell'
      - 'POSTGRES_USER=workwell'
    ports:
      - '5432'

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672' # Porta padrão para comunicação AMQP
      - '15672:15672' # Porta para o painel de gerenciamento
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
